import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <main>
        <header className="text-2xl font-bold px-1 font-outfit">
          {/* <img
            src="https://keyzy-homes.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fe348b114-2bf2-4978-89a8-02d148b89315%2FKeyzy_-_Logo.png?id=495f75c5-1bff-4e7f-8d46-28f7cbf7fa6a&table=block&spaceId=ad2197fa-7ea7-473f-bd0a-35731ba863f4&width=830"
            alt="Keyzy logo"
            width="50"
            height="50"
          ></img> */}
          <h1>Keyzy</h1>
        </header>
        <div>
          <section>
            <h2>Inputs</h2>
            <form className="flex flex-col gap-6">
              <div className="flex gap-20 items-center">
                <label htmlFor="url">URL</label>
                <input
                  type="text"
                  name="url"
                  id="url"
                  className="form-input w-40 h-12"
                />
              </div>
              <div className="flex gap-20 items-center">
                <label htmlFor="discountvasking">
                  Discount vs asking price
                </label>
                <input
                  type="range"
                  name="discountvasking"
                  id="discountvasking"
                  className="w-40 h-12"
                  min="0"
                  max="30"
                  value="15"
                />
              </div>
              <div className="flex gap-20 items-center">
                <label htmlFor="desired-yield">Desired yield</label>
                <input
                  type="text"
                  name="desired-yeild"
                  id="desired-yield"
                  className="form-input w-40 h-12"
                />
              </div>

              <div className="flex gap-20 items-center">
                <label htmlFor="converted-rent">Converted rent rate</label>
                <input
                  type="range"
                  name="converted-rent"
                  id="converted-rent"
                  className="w-40 h-12"
                  min="0"
                  max="30"
                  value="15"
                />
              </div>
              <div className="flex gap-20 items-center">
                <label className="block" htmlFor="duration">Duration</label>
                <div class="inline-block mb-6">
                  <input
                    type="radio"
                    name="duration"
                    id="duration-3"
                    value="3"
                  />
                  <label for="duration-3" class="ml-2">
                    3 years
                  </label>
                </div>
                <div class="inline-block mb-6">
                  <input
                    type="radio"
                    name="duration"
                    id="duration-5"
                    value="5"
                  />
                  <label for="duration-5" class="ml-2">
                    5 years
                  </label>
                </div>
                <div class="inline-block mb-6">
                  <input
                    type="radio"
                    name="duration"
                    id="duration-7"
                    value="7"
                  />
                  <label for="duration-7" class="ml-2">
                    7 years
                  </label>
                </div>
              </div>
            </form>
          </section>
        </div>
      </main>
    </>
  );
}
