import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import getListingMetaData from "../lib/scraper.js";

export default function Home() {
  const [inputs, setInputs] = useState({
    url: "",
    discount: 0,
    desiredYield: 0,
    rentRate: 0,
    duration: 3,
  });
  console.log(inputs);

  function updateDiscount(e) {
    setInputs({ ...inputs, discount: Number(e.target.value) });
  }

  function updateRentRate(e) {
    setInputs({ ...inputs, rentRate: Number(e.target.value) });
  }

  function updateDuration(e) {
    setInputs({ ...inputs, duration: Number(e.target.value) });
  }

  function handleSubmit(e) {
    e.preventDefault();

    const url = e.target[0].value;
    const discount = Number(e.target[1].value);
    const desiredYield = Number(e.target[2].value);
    const rentRate = Number(e.target[3].value);
    const duration = Number(
      Array.from(e.target)
        .slice(4, -1)
        .find((x) => x.checked).value
    );
    setInputs({ ...inputs, url, discount, desiredYield, rentRate, duration });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <main className="p-4 font-outfit">
        <header className="text-2xl font-bold px-1 mb-12 font-outfit">
          <h1>Keyzy</h1>
        </header>
        <div>
          <section>
            <h2 className="text-lg font-bold mb-6">Inputs</h2>
            <form
              className="border-2 border-solid flex flex-col gap-6"
              onSubmit={handleSubmit}
            >
              <div className="flex gap-2 justify-between items-center">
                <label className="w-1/3" htmlFor="url">
                  URL
                </label>
                <input
                  type="text"
                  name="url"
                  id="url"
                  className="form-input w-2/3 h-12"
                />
              </div>
              <div className="flex gap-2 justify-between items-center">
                <label className="w-1/3" htmlFor="discountvasking">
                  Discount vs asking price
                </label>
                <div className="w-2/3 h-12 flex flex-col justify-center">
                  <span className="block text-center">{inputs.discount}%</span>
                  <input
                    type="range"
                    name="discountvasking"
                    id="discountvasking"
                    min="0"
                    max="30"
                    value={inputs.discount}
                    onChange={updateDiscount}
                  />
                </div>
              </div>
              <div className="flex gap-2 justify-between items-center">
                <label className="w-1/3" htmlFor="desired-yield">
                  Desired yield
                </label>
                <input
                  type="text"
                  name="desired-yeild"
                  id="desired-yield"
                  className="form-input w-2/3 h-12"
                />
              </div>

              <div className="flex gap-2 items-center">
                <label className="w-1/3" htmlFor="converted-rent">
                  Converted rent rate
                </label>
                <div className="w-2/3 h-12 flex flex-col justify-center">
                  <span className="block text-center">{inputs.rentRate}%</span>

                  <input
                    type="range"
                    name="converted-rent"
                    id="converted-rent"
                    min="0"
                    max="30"
                    value={inputs.rentRate}
                    onChange={updateRentRate}
                  />
                </div>
              </div>
              <div
                className="flex gap-2 justify-between items-center mb-4"
                onChange={updateDuration}
              >
                <label className="w-1/3 block" htmlFor="duration">
                  Duration
                </label>
                <div className="w-2/3 flex justify-between items-center">
                  <div className="">
                    <input
                      type="radio"
                      name="duration"
                      id="duration-3"
                      value="3"
                      defaultChecked={true}
                    />
                    <label className="w-16 ml-2" htmlFor="duration-3">
                      3 years
                    </label>
                  </div>
                  <div className="">
                    <input
                      type="radio"
                      name="duration"
                      id="duration-5"
                      value="5"
                    />
                    <label className="w-16 ml-2" htmlFor="duration-5">
                      5 years
                    </label>
                  </div>
                  <div className="">
                    <input
                      type="radio"
                      name="duration"
                      id="duration-7"
                      value="7"
                    />
                    <label className="w-16 ml-2" htmlFor="duration-7">
                      7 years
                    </label>
                  </div>
                </div>
              </div>
              <button className="h-12 bg-blue-500 text-white font-bold text-lg w-24 rounded hover:opacity-70">
                Submit
              </button>
            </form>
          </section>
        </div>
      </main>
    </>
  );
}
